spring:
  application:
    name: fruitivia-backend
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  data:
    redis:
      repositories:
        enabled: false

# Actuator Configuration
management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
  info:
    env:
      enabled: true

# OpenAPI / Swagger Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
