version: '3.8'

services:
  db:
    image: postgres:15
    container_name: fruitivia-db
    environment:
      POSTGRES_USER: fruitivia_user
      POSTGRES_PASSWORD: fruitivia_password
      POSTGRES_DB: fruitivia
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  mailpit:
    image: axllent/mailpit
    container_name: fruitivia-mailpit
    ports:
      - "8025:8025"
      - "1025:1025"
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: fruitivia-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana:10.0.3
    container_name: fruitivia-grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false

volumes:
  postgres_data:
  prometheus_data:
  grafana_data:
